#!/usr/bin/env python
"""Turn human-authored query labels into the frozen golden set (data/eval/queries.yaml).

Annotators write ``data/eval/queries.src.yaml`` referencing moments by utterance ranges of the
reference transcript set, e.g. ``runway:70-72`` (inclusive).  This script resolves each range to an
audio-time interval (first utterance start -> last utterance end) and stores the spoken text as an
auditable quote.  The emitted file contains only times + quotes, so the golden set stays valid even if
the transcripts, segmentation or chunking change later (utterance ids are just an authoring aid).

Usage: python scripts/label_helper.py [--transcripts data/transcripts/large-v3-turbo]
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from audiosearch.domain import Transcript  # noqa: E402

REF_RE = re.compile(r"^(?P<file>[a-z_]+):(?P<a>\d+)(?:-(?P<b>\d+))?(?:@(?P<grade>[12]))?$")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--transcripts", default=str(ROOT / "data/transcripts/large-v3-turbo"))
    ap.add_argument("--src", default=str(ROOT / "data/eval/queries.src.yaml"))
    ap.add_argument("--out", default=str(ROOT / "data/eval/queries.yaml"))
    args = ap.parse_args()

    src = yaml.safe_load(Path(args.src).read_text())
    cache: dict[str, Transcript] = {}
    out_queries = []
    for q in src["queries"]:
        rel = []
        for ref in q["relevant"]:
            m = REF_RE.match(ref.strip())
            if not m:
                raise SystemExit(f"{q['id']}: bad reference {ref!r} (expected file:start-end[@grade])")
            fid = m["file"]
            if fid not in cache:
                cache[fid] = Transcript.load(Path(args.transcripts) / f"{fid}.json")
            t = cache[fid]
            a, b = int(m["a"]), int(m["b"] or m["a"])
            if not (0 <= a <= b < len(t.utterances)):
                raise SystemExit(f"{q['id']}: utterance range {a}-{b} out of bounds for {fid}")
            us = t.utterances[a : b + 1]
            quote = " ".join(u.text for u in us)
            rel.append(
                {
                    "file": fid,
                    "start": round(us[0].start, 2),
                    "end": round(us[-1].end, 2),
                    "grade": int(m["grade"] or 2),
                    "quote": quote if len(quote) <= 240 else quote[:237] + "...",
                }
            )
        item = {k: q[k] for k in ("id", "query", "category", "split") if k in q}
        if q.get("role"):
            item["role"] = q["role"]
        if q.get("notes"):
            item["notes"] = q["notes"]
        item["relevant"] = rel
        out_queries.append(item)
    header = (
        "# GENERATED by scripts/label_helper.py from data/eval/queries.src.yaml - edit the source, not this file.\n"
        "# Relevance is expressed as audio-time intervals (seconds) so labels do not depend on chunking.\n"
    )
    body = {
        "version": src.get("version", 1),
        "tolerance_sec": src.get("tolerance_sec", 5.0),
        "description": src.get("description", ""),
        "queries": out_queries,
    }
    Path(args.out).write_text(header + yaml.safe_dump(body, sort_keys=False, allow_unicode=True, width=110))
    cats: dict[str, int] = {}
    for q in out_queries:
        cats[q["category"]] = cats.get(q["category"], 0) + 1
    print(f"wrote {args.out}: {len(out_queries)} queries {cats}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
